
let db={customers:[],loans:[],payments:[],dps:[],dpsPayments:[],settings:{business:"Smart Kisti Manager",phone:"",address:"",footer:"ধন্যবাদ"}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>"৳"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});
const today=()=>new Date().toISOString().slice(0,10);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function init(){db=await window.desktopAPI.load(); normalize(); render(); loadSettings()}
function normalize(){db.customers??=[];db.loans??=[];db.payments??=[];db.dps??=[];db.dpsPayments??=[];db.settings??={business:"Smart Kisti Manager",phone:"",address:"",footer:"ধন্যবাদ"}}
function info(l){let p=db.payments.filter(x=>x.loanId===l.id);return{paid:p.length,due:Math.max(0,Number(l.count)-p.length),amount:p.reduce((a,x)=>a+Number(x.amount||0),0)}}
function dInfo(d){let p=db.dpsPayments.filter(x=>x.dpsId===d.id);return{paid:p.length,due:Math.max(0,Number(d.months)-p.length),amount:p.reduce((a,x)=>a+Number(x.amount||0),0)}}
async function save(){normalize();await window.desktopAPI.save(db);render();toast("সংরক্ষণ হয়েছে")}
function toast(t){let x=$("#toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1500)}
function modal(title,body){$("#modalBody").innerHTML="<h2>"+title+"</h2>"+body;$("#modal").classList.add("show")}
function close(){ $("#modal").classList.remove("show") } $("#close").onclick=close;$("#modal").onclick=e=>{if(e.target.id==="modal")close()}
function customerOptions(){return '<option value="">সাধারণ</option>'+db.customers.map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.phone)}</option>`).join("")}
function render(){
 let collection=db.payments.reduce((a,p)=>a+Number(p.amount||0),0), dps=db.dpsPayments.reduce((a,p)=>a+Number(p.amount||0),0);
 let outstanding=db.loans.reduce((a,l)=>a+info(l).due*Number(l.per||0),0), active=db.loans.filter(l=>info(l).due>0).length,done=db.loans.length-active,dueCount=db.loans.reduce((a,l)=>a+info(l).due,0);
 $("#xCustomers").textContent=db.customers.length;$("#xCollection").textContent=money(collection);$("#xOutstanding").textContent=money(outstanding);$("#xDps").textContent=money(dps);$("#xActive").textContent=active;$("#xDone").textContent=done;$("#xDpsPlans").textContent=db.dps.filter(d=>dInfo(d).due>0).length;$("#xDueCount").textContent=dueCount;
 let vals=[["Kisti Collection",collection],["Kisti Outstanding",outstanding],["DPS Deposited",dps]], max=Math.max(...vals.map(x=>x[1]),1);
 $("#bars").innerHTML=vals.map(v=>`<div class=barrow><span>${v[0]}</span><div class=bar><i style="width:${v[1]/max*100}%"></i></div><b>${money(v[1])}</b></div>`).join("");
 renderCustomers();renderLoans();renderDps();renderPayments();renderDue();renderReports();loadSettings()
}
function renderCustomers(){let q=($("#customerSearch")?.value||"").toLowerCase(),a=db.customers.filter(c=>(c.name+" "+c.phone+" "+c.address).toLowerCase().includes(q));$("#customerTable").innerHTML=a.length?`<table><tr><th>নাম</th><th>মোবাইল</th><th>ঠিকানা</th><th>কিস্তি</th><th>DPS</th></tr>${a.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${esc(c.address)}</td><td>${db.loans.filter(l=>l.customerId===c.id).length}</td><td>${db.dps.filter(d=>d.customerId===c.id).length}</td></tr>`).join("")}</table>`:"<div class=empty>কোনো Customer নেই</div>"}
function renderLoans(){let q=($("#loanSearch")?.value||"").toLowerCase(),f=$("#loanFilter")?.value||"all",a=db.loans.filter(l=>(l.name+" "+l.customerName).toLowerCase().includes(q)).filter(l=>f==="all"||(f==="active"&&info(l).due)||(f==="done"&&!info(l).due));$("#loanTable").innerHTML=a.length?`<table><tr><th>Account</th><th>Customer</th><th>Per</th><th>Progress</th><th>Due</th><th>Status</th><th></th></tr>${a.map(l=>{let x=info(l),pc=x.paid/Number(l.count)*100;return `<tr><td><b>${esc(l.name)}</b></td><td>${esc(l.customerName)}</td><td>${money(l.per)}</td><td>${x.paid}/${l.count}<div class=progress><i style="width:${Math.min(100,pc)}%"></i></div></td><td>${money(x.due*l.per)}</td><td><span class="badge ${x.due?'due':'paid'}">${x.due?'চলমান':'সম্পূর্ণ'}</span></td><td><button class="btn alt collect" data-id="${l.id}">Collect</button></td></tr>`}).join("")}</table>`:"<div class=empty>কোনো Kisti Account নেই</div>"}
function renderDps(){let total=db.dps.reduce((a,d)=>a+d.monthly*d.months,0),paid=db.dpsPayments.reduce((a,p)=>a+Number(p.amount||0),0),mat=db.dps.reduce((a,d)=>a+d.monthly*d.months*(1+Number(d.rate||0)/100),0);$("#dTotal").textContent=money(total);$("#dPaid").textContent=money(paid);$("#dDue").textContent=money(Math.max(0,total-paid));$("#dMat").textContent=money(mat);$("#dpsTable").innerHTML=db.dps.length?`<table><tr><th>Plan</th><th>Customer</th><th>Monthly</th><th>Progress</th><th>Maturity</th><th>Status</th><th></th></tr>${db.dps.map(d=>{let x=dInfo(d),pc=x.paid/d.months*100;return `<tr><td><b>${esc(d.name)}</b></td><td>${esc(d.customerName)}</td><td>${money(d.monthly)}</td><td>${x.paid}/${d.months}<div class=progress><i style="width:${Math.min(100,pc)}%"></i></div></td><td>${money(d.monthly*d.months*(1+Number(d.rate||0)/100))}</td><td><span class="badge ${x.due?'due':'paid'}">${x.due?'চলমান':'সম্পূর্ণ'}</span></td><td><button class="btn alt dcollect" data-id="${d.id}">Deposit</button></td></tr>`}).join("")}</table>`:"<div class=empty>কোনো DPS নেই</div>"}
function renderPayments(){let q=($("#paymentSearch")?.value||"").toLowerCase(),a=db.payments.filter(p=>(p.loanName+" "+p.date).toLowerCase().includes(q));$("#paymentTable").innerHTML=a.length?`<table><tr><th>Date</th><th>Account</th><th>Installment</th><th>Amount</th></tr>${a.slice().reverse().map(p=>`<tr><td>${p.date}</td><td>${esc(p.loanName)}</td><td>${p.no}</td><td>${money(p.amount)}</td></tr>`).join("")}</table>`:"<div class=empty>কোনো Payment নেই</div>"}
function renderDue(){let q=($("#dueSearch")?.value||"").toLowerCase(),a=[];db.loans.forEach(l=>{let x=info(l);if(x.due)a.push({id:l.id,name:l.name,customer:l.customerName,no:x.paid+1,amount:l.per,date:l.start})});a=a.filter(r=>(r.name+" "+r.customer).toLowerCase().includes(q));$("#dueTable").innerHTML=a.length?`<table><tr><th>Account</th><th>Customer</th><th>Next No</th><th>Amount</th><th>Start Date</th><th></th></tr>${a.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.customer)}</td><td>${r.no}</td><td>${money(r.amount)}</td><td>${r.date}</td><td><button class="btn alt collect" data-id="${r.id}">Collect</button></td></tr>`).join("")}</table>`:"<div class=empty>কোনো Due নেই</div>"}
function renderReports(){let k=db.payments.reduce((a,p)=>a+Number(p.amount||0),0),d=db.dpsPayments.reduce((a,p)=>a+Number(p.amount||0),0),due=db.loans.reduce((a,l)=>a+info(l).due*l.per,0);$("#report").innerHTML=`<div class=grid4><div class=kpi><small>Kisti Collection</small><b>${money(k)}</b></div><div class=kpi><small>DPS Deposited</small><b>${money(d)}</b></div><div class=kpi><small>Outstanding</small><b>${money(due)}</b></div><div class=kpi><small>Total Transactions</small><b>${db.payments.length+db.dpsPayments.length}</b></div></div><br><div class=notice>রিপোর্ট CSV-তে export করে Excel/Google Sheets-এ ব্যবহার করতে পারবেন।</div>`}
function loadSettings(){let f=$("#settingsForm");if(f){let s=db.settings;f.business.value=s.business||"";f.phone.value=s.phone||"";f.address.value=s.address||"";f.footer.value=s.footer||""}}
function addCustomer(){modal("নতুন Customer",`<form id=form class=form><label>নাম<input name=name required></label><label>মোবাইল<input name=phone></label><label>ঠিকানা<input name=address></label><button class=btn>Save</button></form>`)}
function addLoan(){modal("নতুন Kisti Account",`<form id=form class=form><label>Customer<select name=customer>${customerOptions()}</select></label><label>Account Name<input name=name required></label><div class=grid2><label>মোট কিস্তি<input name=count type=number min=1 required></label><label>প্রতি কিস্তি<input name=per type=number min=1 required></label></div><label>Start Date<input name=start type=date value="${today()}"></label><button class=btn>Create</button></form>`)}
function addDps(){modal("নতুন DPS",`<form id=form class=form><label>Customer<select name=customer>${customerOptions()}</select></label><label>DPS Name<input name=name required></label><div class=grid2><label>মাসিক জমা<input name=monthly type=number min=1 required></label><label>মেয়াদ (মাস)<input name=months type=number min=1 required></label></div><div class=grid2><label>মুনাফা %<input name=rate type=number step=.01 value=0></label><label>Start<input name=start type=date value="${today()}"></label></div><button class=btn>Create DPS</button></form>`)}
function collectLoan(id){let l=db.loans.find(x=>x.id===id),n=info(l).paid+1;modal("কিস্তি জমা",`<form id=form class=form><input type=hidden name=loan value="${id}"><div class=grid2><label>কিস্তি নং<input name=no type=number value="${n}"></label><label>তারিখ<input name=date type=date value="${today()}"></label></div><label>পরিমাণ<input name=amount type=number value="${l.per}"></label><button class=btn>Save Payment</button></form>`)}
function collectDps(id){let d=db.dps.find(x=>x.id===id),n=dInfo(d).paid+1;modal("DPS Deposit",`<form id=form class=form><input type=hidden name=dps value="${id}"><div class=grid2><label>কিস্তি নং<input name=no type=number value="${n}"></label><label>তারিখ<input name=date type=date value="${today()}"></label></div><label>জমার পরিমাণ<input name=amount type=number value="${d.monthly}"></label><button class=btn>Save Deposit</button></form>`)}
$("#addCustomer").onclick=addCustomer;$("#addLoan").onclick=addLoan;$("#addDps").onclick=addDps;$("#payBtn").onclick=()=>db.loans[0]?collectLoan(db.loans[0].id):toast("আগে Kisti Account তৈরি করুন");$("#dpsDeposit").onclick=()=>db.dps[0]?collectDps(db.dps[0].id):toast("আগে DPS তৈরি করুন");
document.addEventListener("click",e=>{let a=e.target.closest(".collect");if(a)collectLoan(Number(a.dataset.id));let d=e.target.closest(".dcollect");if(d)collectDps(Number(d.dataset.id))});
document.addEventListener("submit",async e=>{if(e.target.id==="settingsForm"){e.preventDefault();let f=new FormData(e.target);db.settings={business:f.get("business"),phone:f.get("phone"),address:f.get("address"),footer:f.get("footer")};await save();return}if(e.target.id!=="form")return;e.preventDefault();let f=new FormData(e.target),title=$("#modalBody h2").textContent;
 if(title==="নতুন Customer")db.customers.push({id:Date.now(),name:f.get("name"),phone:f.get("phone"),address:f.get("address")});
 else if(title==="নতুন Kisti Account"){let c=db.customers.find(x=>String(x.id)===f.get("customer"));db.loans.push({id:Date.now(),customerId:c?.id||null,customerName:c?.name||"সাধারণ",name:f.get("name"),count:+f.get("count"),per:+f.get("per"),start:f.get("start")})}
 else if(title==="নতুন DPS"){let c=db.customers.find(x=>String(x.id)===f.get("customer"));db.dps.push({id:Date.now(),customerId:c?.id||null,customerName:c?.name||"সাধারণ",name:f.get("name"),monthly:+f.get("monthly"),months:+f.get("months"),rate:+f.get("rate"),start:f.get("start")})}
 else if(title==="কিস্তি জমা"){let l=db.loans.find(x=>x.id==f.get("loan")),no=+f.get("no");if(db.payments.some(p=>p.loanId===l.id&&p.no===no))return toast("এই কিস্তি ইতোমধ্যে জমা হয়েছে");db.payments.push({id:Date.now(),loanId:l.id,loanName:l.name,no,date:f.get("date"),amount:+f.get("amount")})}
 else if(title==="DPS Deposit"){let d=db.dps.find(x=>x.id==f.get("dps")),no=+f.get("no");if(db.dpsPayments.some(p=>p.dpsId===d.id&&p.no===no))return toast("এই DPS কিস্তি ইতোমধ্যে জমা হয়েছে");db.dpsPayments.push({id:Date.now(),dpsId:d.id,dpsName:d.name,no,date:f.get("date"),amount:+f.get("amount")})}
 close();await save()});
$$(".nav").forEach(n=>n.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");$$(".page").forEach(p=>p.classList.remove("active"));$("#"+n.dataset.page).classList.add("active");$("#title").textContent=n.innerText.trim()});
$("#customerSearch").oninput=renderCustomers;$("#loanSearch").oninput=renderLoans;$("#loanFilter").onchange=renderLoans;$("#paymentSearch").oninput=renderPayments;$("#dueSearch").oninput=renderDue;
$("#backupBtn").onclick=async()=>{let p=await window.desktopAPI.backup();if(p)toast("Backup saved")};$("#restoreBtn").onclick=async()=>{if(confirm("Backup restore করলে বর্তমান data replace হবে। Continue?")){if(await window.desktopAPI.restore()){db=await window.desktopAPI.load();normalize();render();toast("Restore complete")}}};$("#openFolder").onclick=()=>window.desktopAPI.folder();
$("#copyDue").onclick=()=>{navigator.clipboard?.writeText($("#dueTable").innerText);toast("Due list copied")};$("#printPayments").onclick=()=>window.print();$("#printReport").onclick=()=>window.print();
$("#csvBtn").onclick=()=>{let rows=[["Type","Name","Date","Amount","Installment"],...db.payments.map(p=>["Kisti",p.loanName,p.date,p.amount,p.no]),...db.dpsPayments.map(p=>["DPS",p.dpsName,p.date,p.amount,p.no])];let csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="smart-kisti-report.csv";a.click()};
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="b"){e.preventDefault();$("#backupBtn").click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="p"){e.preventDefault();window.print()}});
init();
